@extends('layouts.platform')
@section('title','Companies')
@section('heading','Companies & registrations')
@section('content')
<div class="card mb-4"><div class="card-body">
<div class="d-flex justify-content-between"><div><h5>Create company</h5><p class="text-muted">Creates a central admin and fresh isolated database.</p></div><button class="btn btn-primary" data-toggle="collapse" data-target="#newCompany">New company</button></div>
<div class="collapse" id="newCompany"><form method="post" action="{{ route('superadmin.tenants.store') }}">@csrf<div class="form-row">
@foreach([['name','Company name','text'],['contact_email','Contact email','email'],['admin_name','Admin name','text'],['admin_email','Admin email','email'],['admin_phone','Admin phone','text'],['admin_password','Admin password','password']] as $field)<div class="col-md-4 mb-2"><input class="form-control" type="{{ $field[2] }}" name="{{ $field[0] }}" placeholder="{{ $field[1] }}" {{ in_array($field[0],['name','admin_name','admin_email','admin_password'])?'required':'' }}></div>@endforeach
<div class="col-md-3"><select class="form-control" name="plan"><option value="trial">Trial</option><option value="standard">Standard</option><option value="professional">Professional</option><option value="enterprise">Enterprise</option></select></div><div class="col-md-3"><input class="form-control" name="timezone" value="Asia/Kolkata" required></div><div class="col-md-2"><input class="form-control" name="locale" value="en" required></div><div class="col-md-2"><input class="form-control" type="number" min="1" name="max_users" placeholder="User limit"></div><div class="col-md-2"><input class="form-control" type="date" name="trial_ends_at"></div><div class="col-md-2"><button class="btn btn-primary">Create & provision</button></div></div></form></div>
</div></div>
@foreach($tenants as $tenant)
<div class="card mb-3"><div class="card-body">
<div class="d-flex justify-content-between flex-wrap"><div><h5>{{ $tenant->name }}</h5><span class="text-muted">{{ $tenant->contact_email ?: 'No contact email' }} · 1 Admin + {{ max($tenant->users_count - 1, 0) }} users · {{ $tenant->database_name ?: 'No database' }}</span></div><div><span class="badge badge-{{ $tenant->approval_status==='approved'?'success':($tenant->approval_status==='pending'?'warning':'danger') }}">{{ ucfirst($tenant->approval_status) }}</span> <span class="badge badge-{{ $tenant->provision_status }}">DB {{ $tenant->provision_status }}</span></div></div>
<p class="mt-2 mb-2"><strong>Plan:</strong> {{ ucfirst($tenant->plan) }} · <strong>Expires:</strong> {{ optional($tenant->trial_ends_at)->format('d M Y') ?: 'No expiry' }} · <strong>Admin:</strong> {{ $tenant->admin?->email ?: 'Not assigned' }}</p>
@if($tenant->provision_error)<div class="alert alert-danger"><small>{{ $tenant->provision_error }}</small></div>@endif
<div class="d-flex flex-wrap" style="gap:8px"><a class="btn btn-sm btn-outline-primary" href="{{ route('superadmin.users.index',$tenant) }}">Manage users</a>
@if($tenant->approval_status==='pending')<form method="post" action="{{ route('superadmin.tenants.approve',$tenant) }}">@csrf<button class="btn btn-sm btn-success">Approve</button></form><button class="btn btn-sm btn-outline-danger" data-toggle="collapse" data-target="#reject{{ $tenant->id }}">Reject</button>@endif
<form method="post" action="{{ route('superadmin.tenants.provision',$tenant) }}">@csrf<button class="btn btn-sm btn-outline-secondary">{{ $tenant->provision_status==='ready'?'Re-provision safely':'Retry provisioning' }}</button></form>
@if($tenant->database_name)<form method="post" action="{{ route('superadmin.tenants.health',$tenant) }}">@csrf<button class="btn btn-sm btn-outline-secondary">Health check</button></form>@endif
</div>
<div class="collapse mt-2" id="reject{{ $tenant->id }}"><form method="post" action="{{ route('superadmin.tenants.reject',$tenant) }}" class="form-inline">@csrf<input class="form-control mr-2" name="rejection_reason" placeholder="Reason required" required><button class="btn btn-danger">Confirm rejection</button></form></div>
<hr><form method="post" action="{{ route('superadmin.tenants.update',$tenant) }}">@csrf @method('PUT')<input type="hidden" name="slug" value="{{ $tenant->slug }}"><input type="hidden" name="timezone" value="{{ $tenant->timezone }}"><input type="hidden" name="locale" value="{{ $tenant->locale }}"><div class="form-row"><div class="col-md-3"><input class="form-control" name="name" value="{{ $tenant->name }}" required></div><div class="col-md-3"><input class="form-control" type="email" name="contact_email" value="{{ $tenant->contact_email }}"></div><div class="col-md-2"><select class="form-control" name="plan">@foreach(['trial','standard','professional','enterprise'] as $plan)<option value="{{ $plan }}" @selected($tenant->plan===$plan)>{{ ucfirst($plan) }}</option>@endforeach</select></div><div class="col-md-2"><input class="form-control" type="date" name="trial_ends_at" value="{{ optional($tenant->trial_ends_at)->format('Y-m-d') }}"></div><div class="col-md-1"><input class="form-control" type="number" min="1" name="max_users" value="{{ $tenant->max_users }}"></div><div class="col-md-1"><select class="form-control" name="status"><option @selected($tenant->status==='Active')>Active</option><option @selected($tenant->status==='Inactive')>Inactive</option></select></div></div><button class="btn btn-sm btn-outline-primary mt-2">Save settings</button></form>
</div></div>
@endforeach
@endsection
