<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>Company | CRM</title>
    <link rel="stylesheet" href="{{ asset('vendors/css/vendor.bundle.base.css') }}"><link rel="stylesheet" href="{{ asset('css/vertical-layout-light/style.css') }}"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        .hero,.panel{background:#fff;border:1px solid #e5e7eb;border-radius:14px;box-shadow:0 8px 24px rgba(15,23,42,.05)}.hero{padding:20px 22px;margin-bottom:18px}.hero h3{font-weight:750;margin:4px 0}.panel{padding:18px;margin-bottom:18px}.panel h5{font-weight:700;margin-bottom:14px}.meta{color:#64748b;font-size:12px}.field{display:flex;justify-content:space-between;gap:15px;padding:9px 0;border-bottom:1px solid #f1f5f9;font-size:13px}.field:last-child{border:0}.field span:first-child{color:#64748b}.metric-card{background:#f8fafc;border-radius:10px;padding:14px;text-align:center}.metric-card strong{display:block;font-size:22px;color:#1d4ed8}.related-row{padding:10px 0;border-bottom:1px solid #f1f5f9;font-size:13px}.related-row:last-child{border:0}
    </style>
</head>
<body><div class="container-scroller">@include('include.header')<div class="container-fluid page-body-wrapper">@include('include.sidebar')<div class="content-wrapper">
    <div class="hero"><a href="{{ route('companies.index') }}" class="meta"><i class="fa fa-arrow-left"></i> Back to Companies</a><h3 id="companyName">Loading…</h3><div class="meta" id="companySubtitle"></div></div>
    <div class="row"><div class="col-lg-4"><div class="panel"><h5>Company Information</h5><div id="companyInfo"></div></div></div><div class="col-lg-8">
        <div class="row mb-3"><div class="col-4"><div class="metric-card"><strong id="contactCount">0</strong>Contacts</div></div><div class="col-4"><div class="metric-card"><strong id="leadCount">0</strong>Leads</div></div><div class="col-4"><div class="metric-card"><strong id="dealCount">0</strong>Deals</div></div></div>
        <div class="panel"><h5>Contacts</h5><div id="contactsList"></div></div><div class="panel"><h5>Recent Leads</h5><div id="leadsList"></div></div><div class="panel"><h5>Recent Deals</h5><div id="dealsList"></div></div>
    </div></div>@include('include.footer')
</div></div></div>
<script src="{{ asset('vendors/js/vendor.bundle.base.js') }}"></script><script>
    const companyId={{ (int) $companyId }};const esc=v=>$('<div>').text(v??'').html();const empty=label=>`<p class="text-muted mb-0">No ${label} linked yet.</p>`;
    $.get("{{ url('companies') }}/"+companyId+'/detail',r=>{const c=r.data;$('#companyName').text(c.name);$('#companySubtitle').text([c.industry,c.status].filter(Boolean).join(' · '));$('#contactCount').text(c.contacts_count);$('#leadCount').text(c.leads_count);$('#dealCount').text(c.deals_count);$('#companyInfo').html(`<div class="field"><span>Owner</span><strong>${esc(c.owner?.name||'Unassigned')}</strong></div><div class="field"><span>Email</span><strong>${esc(c.email||'-')}</strong></div><div class="field"><span>Phone</span><strong>${esc(c.phone||'-')}</strong></div><div class="field"><span>Website</span><strong>${c.website?`<a href="${esc(c.website)}" target="_blank" rel="noopener">Visit</a>`:'-'}</strong></div><div class="field"><span>Location</span><strong>${esc([c.city,c.state,c.country].filter(Boolean).join(', ')||'-')}</strong></div><div class="field"><span>GST</span><strong>${esc(c.gst_number||'-')}</strong></div>`);$('#contactsList').html(c.contacts.length?c.contacts.map(x=>`<div class="related-row"><strong>${esc(x.name)}</strong>${x.is_primary?' <i class="fa fa-star text-warning"></i>':''}<br><span class="meta">${esc(x.designation||'')} ${esc(x.email||x.phone||'')}</span></div>`).join(''):empty('contacts'));$('#leadsList').html(c.leads.length?c.leads.map(x=>`<div class="related-row"><a href="{{ url('leads') }}/${x.id}"><strong>${esc(x.name)}</strong></a><span class="float-right meta">${esc(x.lead_status)}</span><br><span class="meta">Owner: ${esc(x.assigned_user?.name||'Unassigned')}</span></div>`).join(''):empty('leads'));$('#dealsList').html(c.deals.length?c.deals.map(x=>`<div class="related-row"><a href="{{ url('deals') }}/${x.id}"><strong>${esc(x.name)}</strong></a><span class="float-right meta">${esc(x.currency||'')} ${Number(x.amount||0).toLocaleString('en-IN')}</span><br><span class="meta">${esc(x.stage?.name||x.status)}</span></div>`).join(''):empty('deals'))}).fail(()=>$('#companyName').text('Company not found'));
</script></body></html>
