<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Reports & Analytics</title>
<link rel="stylesheet" href="{{ asset('vendors/feather/feather.css') }}"><link rel="stylesheet" href="{{ asset('vendors/ti-icons/css/themify-icons.css') }}"><link rel="stylesheet" href="{{ asset('vendors/css/vendor.bundle.base.css') }}"><link rel="stylesheet" href="{{ asset('css/vertical-layout-light/style.css') }}"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>.report-card{border:0;border-radius:14px;box-shadow:0 7px 25px rgba(30,64,175,.08)}.metric-value{font-size:25px;font-weight:700;color:#1e3a8a}.metric-label{font-size:12px;color:#64748b;text-transform:uppercase;letter-spacing:.04em}.chart-box{height:310px}.filter-bar{display:flex;gap:10px;align-items:end;flex-wrap:wrap}.filter-bar label{font-size:12px;color:#64748b}</style></head>
<body><div class="container-scroller">@include('include.header')<div class="container-fluid page-body-wrapper">@include('include.sidebar')<div class="main-panel"><div class="content-wrapper">
<div class="d-flex justify-content-between align-items-start flex-wrap mb-4"><div><h3 class="mb-1">Reports & Analytics</h3><p class="text-muted">Funnel, revenue, acquisition, and team performance.</p></div><div class="filter-bar"><div><label>From</label><input id="from" type="date" class="form-control"></div><div><label>To</label><input id="to" type="date" class="form-control"></div><button class="btn btn-primary" id="runReport">Run report</button></div></div>
<div class="row" id="metrics">@foreach(['Leads created','Deals created','Won deals','Win rate','Pipeline value','Booked revenue','Cash collected'] as $label)<div class="col-xl col-md-4 col-sm-6 mb-3"><div class="card report-card h-100"><div class="card-body"><div class="metric-label">{{ $label }}</div><div class="metric-value">—</div></div></div></div>@endforeach</div>
<div class="row"><div class="col-lg-7 mb-4"><div class="card report-card"><div class="card-body"><h5>Revenue and collections</h5><div class="chart-box"><canvas id="trendChart"></canvas></div></div></div></div><div class="col-lg-5 mb-4"><div class="card report-card"><div class="card-body"><h5>Lead sources</h5><div class="chart-box"><canvas id="sourceChart"></canvas></div></div></div></div></div>
<div class="row"><div class="col-lg-6 mb-4"><div class="card report-card"><div class="card-body"><h5>Deal funnel</h5><div class="chart-box"><canvas id="funnelChart"></canvas></div></div></div></div><div class="col-lg-6 mb-4"><div class="card report-card"><div class="card-body"><h5>Owner performance</h5><div class="table-responsive"><table class="table"><thead><tr><th>Owner</th><th>Deals</th><th>Won</th><th>Won value</th></tr></thead><tbody id="ownerRows"></tbody></table></div></div></div></div></div>
</div>@include('include.footer')</div></div></div><script src="{{ asset('vendors/js/vendor.bundle.base.js') }}"></script><script src="{{ asset('vendors/chart.js/Chart.min.js') }}"></script><script>
(() => {let charts={};const money=new Intl.NumberFormat(undefined,{style:'currency',currency:'INR',maximumFractionDigits:0});const esc=v=>$('<div>').text(v??'').html();const metricKeys=['leads_created','deals_created','won_deals','win_rate','pipeline_value','booked_revenue','cash_collected'];
function draw(id,type,labels,datasets,options={}){if(charts[id])charts[id].destroy();charts[id]=new Chart(document.getElementById(id),{type,data:{labels,datasets},options:{responsive:true,maintainAspectRatio:false,legend:{position:'bottom'},...options}})}
function run(){const p=new URLSearchParams({from:$('#from').val(),to:$('#to').val()});$.get(`{{ route('reports.data') }}?${p}`,r=>{const vals=metricKeys.map(k=>r.summary[k]);$('#metrics .metric-value').each((i,e)=>{$(e).text(i===3?`${vals[i]}%`:(i>=4?money.format(vals[i]):vals[i]))});draw('trendChart','line',r.trend.labels,[{label:'Booked revenue',data:r.trend.revenue,borderColor:'#2563eb',backgroundColor:'rgba(37,99,235,.1)',fill:true},{label:'Cash collected',data:r.trend.cash,borderColor:'#10b981',backgroundColor:'rgba(16,185,129,.1)',fill:true}]);draw('sourceChart','doughnut',r.sources.map(x=>x.label),[{data:r.sources.map(x=>x.total),backgroundColor:['#2563eb','#10b981','#f59e0b','#ef4444','#8b5cf6','#06b6d4','#84cc16','#f97316','#64748b','#ec4899']}]);draw('funnelChart','horizontalBar',r.funnel.map(x=>x.name),[{label:'Deals',data:r.funnel.map(x=>x.total),backgroundColor:r.funnel.map(x=>x.color||'#2563eb')}],{scales:{xAxes:[{ticks:{beginAtZero:true,precision:0}}]}});$('#ownerRows').html(r.owners.map(o=>`<tr><td>${esc(o.name)}</td><td>${o.deals}</td><td>${o.won}</td><td>${esc(money.format(o.won_value))}</td></tr>`).join('')||'<tr><td colspan="4" class="text-muted text-center">No results</td></tr>');}).fail(x=>alert(x.responseJSON?.message||'Unable to load report.'))}
const today=new Date();const from=new Date();from.setDate(today.getDate()-29);$('#to').val(today.toISOString().slice(0,10));$('#from').val(from.toISOString().slice(0,10));$('#runReport').on('click',run);run();})();
</script></body></html>
