<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="csrf-token" content="{{ csrf_token() }}"><title>Notifications</title>
<link rel="stylesheet" href="{{ asset('vendors/feather/feather.css') }}"><link rel="stylesheet" href="{{ asset('vendors/ti-icons/css/themify-icons.css') }}"><link rel="stylesheet" href="{{ asset('vendors/css/vendor.bundle.base.css') }}"><link rel="stylesheet" href="{{ asset('css/vertical-layout-light/style.css') }}"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    /* Same modernization pattern as the rest of this pass. */
    .crm-page-header{background:#fff;padding:26px 28px;border-radius:16px;box-shadow:0 8px 24px rgba(15,23,42,.06);margin-bottom:24px;display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:16px}
    .crm-page-header h3{margin:0 0 6px;font-weight:700;font-size:22px;color:#111827}.crm-page-header p{margin:0;color:#6b7280;font-size:14px}
    .crm-page-header .btn{border-radius:10px;padding:10px 20px;font-weight:600}
    .notification-card{border:0;border-radius:16px;box-shadow:0 8px 24px rgba(15,23,42,.06);overflow:hidden}.notification-item{display:flex;gap:16px;padding:20px 22px;border-bottom:1px solid #edf2f7;cursor:pointer}.notification-item:hover{background:#f8fbff}.notification-item.unread{background:#eff6ff}.notification-icon{width:42px;height:42px;border-radius:50%;display:flex;align-items:center;justify-content:center;background:#dbeafe;color:#2563eb}.notification-message{font-weight:600;color:#1f2937;font-size:15px}.notification-time{font-size:13px;color:#64748b}
</style></head>
<body><div class="container-scroller">@include('include.header')<div class="container-fluid page-body-wrapper">@include('include.sidebar')<div class="main-panel"><div class="content-wrapper"><div class="crm-page-header"><div><h3>Notifications</h3><p>Reminders and important CRM updates.</p></div><button class="btn btn-outline-primary" id="readAll">Mark all read</button></div><div class="notification-card" id="notificationList"><div class="p-5 text-center text-muted">Loading…</div></div></div>@include('include.footer')</div></div></div>
<script src="{{ asset('vendors/js/vendor.bundle.base.js') }}"></script><script>(()=>{const csrf=document.querySelector('meta[name="csrf-token"]').content;const esc=v=>$('<div>').text(v??'').html();function load(){$.get(`{{ route('notifications.data') }}`,r=>{$('#notificationList').html(r.data.map(n=>`<div class="notification-item ${n.read_at?'':'unread'}" data-id="${n.id}"><div class="notification-icon"><i class="fa fa-bell"></i></div><div><div class="notification-message">${esc(n.data.title||'Notification')}</div><div>${esc(n.data.message||'')}</div><div class="notification-time">${esc(new Date(n.created_at).toLocaleString())}</div></div></div>`).join('')||'<div class="p-5 text-center text-muted"><i class="fa fa-bell-slash-o fa-2x"></i><br>No notifications yet.</div>')})}$(document).on('click','.notification-item',function(){$.ajax({url:`{{ url('/notifications') }}/${$(this).data('id')}/read`,method:'POST',headers:{'X-CSRF-TOKEN':csrf}}).done(r=>window.location.href=r.url)});$('#readAll').on('click',()=>$.ajax({url:`{{ route('notifications.read_all') }}`,method:'POST',headers:{'X-CSRF-TOKEN':csrf}}).done(load));load()})();</script></body></html>
