@extends('layouts.platform')
@section('title',$tenant->name.' users')
@section('heading',$tenant->name.' · users')
@section('content')
<div class="card mb-4"><div class="card-body"><h5>Tenant Admin</h5><p>{{ $tenant->admin?->name }} · {{ $tenant->admin?->email }}</p><p class="text-muted">Every tenant has exactly one protected Admin. All other accounts count as users.</p>
<form method="post" action="{{ route('superadmin.users.transfer_admin',$tenant) }}" class="form-inline">@csrf<select name="user_id" class="form-control mr-2" required>@foreach($tenant->users as $member)<option value="{{ $member->id }}" @selected($tenant->admin_user_id===$member->id)>{{ $member->name }} ({{ $member->email }})</option>@endforeach</select><button class="btn btn-warning" onclick="return confirm('Transfer tenant administration?')">Transfer Admin</button></form></div></div>
@if($roles->isEmpty())<div class="alert alert-info">The tenant Admin must create a custom role before additional users can be added.</div>@else
<div class="card mb-4"><div class="card-body"><h5>Add tenant user</h5><form method="post" action="{{ route('superadmin.users.store',$tenant) }}" class="form-row">@csrf<div class="col-md-2"><input class="form-control" name="name" placeholder="Name" required></div><div class="col-md-3"><input class="form-control" type="email" name="email" placeholder="Email" required></div><div class="col-md-2"><input class="form-control" name="phone" placeholder="Phone"></div><div class="col-md-2"><select class="form-control" name="role">@foreach($roles as $role)<option>{{ $role }}</option>@endforeach</select></div><div class="col-md-2"><input class="form-control" type="password" name="password" placeholder="Password" required></div><div class="col-md-1"><button class="btn btn-primary">Add</button></div></form></div></div>@endif
<div class="card"><div class="card-body"><div class="table-responsive"><table class="table"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Update</th></tr></thead><tbody>
@foreach($tenant->users as $member)<tr><td>{{ $member->name }}<br><small>{{ $member->email }}</small></td><td>{{ $tenant->admin_user_id===$member->id ? 'Admin' : ($member->getRoleNames()->first() ?: 'Unassigned') }}</td><td>{{ $member->status }}</td><td><form method="post" action="{{ route('superadmin.users.update',[$tenant,$member]) }}" class="form-row">@csrf @method('PUT')<input type="hidden" name="name" value="{{ $member->name }}"><input type="hidden" name="email" value="{{ $member->email }}"><input type="hidden" name="phone" value="{{ $member->phone }}"><div class="col"><select class="form-control form-control-sm" name="status">@foreach(['Active','Inactive','Block'] as $status)<option @selected($member->status===$status)>{{ $status }}</option>@endforeach</select></div><div class="col"><select class="form-control form-control-sm" name="role" @disabled($tenant->admin_user_id===$member->id)>@if($tenant->admin_user_id===$member->id)<option>Admin</option>@else @foreach($roles as $role)<option @selected($member->hasRole($role))>{{ $role }}</option>@endforeach @endif</select></div><div class="col"><button class="btn btn-sm btn-outline-primary">Save</button></div></form></td></tr>@endforeach
</tbody></table></div></div></div>
@endsection
